# Generated by Django 4.1.7 on 2023-03-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Employee')])),
                ('secret_key', models.TextField()),
            ],
        ),
    ]
